version: "3"

services:
  bot:
    build: .
    image: skyblue3350/discord-bot
    environment:
      DISCORDBOT_LOGLEVEL: DEBUG
      DISCORDBOT_TOKEN: ${DISCORDBOT_TOKEN}
    volumes:
      - ./music:/app/music
